name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    name: Build Unity Project for Android
    runs-on: ubuntu-latest

    env:
      UNITY_VERSION: ${{ env.UNITY_VERSION }}
      TARGET_PLATFORM: ${{ env.TARGET_PLATFORM }}
      PROJECT_PATH: ${{ env.PROJECT_PATH }}

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      # 2. Cache Unity Library folder (to speed up builds)
      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ env.TARGET_PLATFORM }}-${{ hashFiles('**/Assets/**') }}
          restore-keys: |
            Library-${{ env.TARGET_PLATFORM }}-
            Library-

      # 3. Activate Unity License
      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # 4. Build Android APK or AAB
      - name: Build Unity Project for Android
        uses: game-ci/unity-builder@v4
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: ${{ env.TARGET_PLATFORM }}
          customParameters: -buildAppBundle false

      # 5. Upload APK/AAB Build as Artifact
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Android-Build
          path: build
