name: Unity Generic Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-unity:
    name: Build Unity Project for ${{ matrix.targetPlatform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        targetPlatform: [StandaloneWindows64, StandaloneLinux64, Android, iOS, WebGL]
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true # If your project uses large files like textures or assets
          fetch-depth: 0

      # 2. Cache Unity Library to speed up builds
      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('**/Assets/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-

      # 3. Activate Unity License
      - name: Activate Unity License
        uses: game-ci/unity-activate@v4
        with:
          unityVersion: ${{ secrets.UNITY_VERSION }} # Dynamically configure Unity version
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # 4. Build the project
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        with:
          projectPath: . # Root of the Unity project
          unityVersion: ${{ secrets.UNITY_VERSION }}
          targetPlatform: ${{ matrix.targetPlatform }} # Dynamic platform from matrix
          customParameters: ${{ secrets.CUSTOM_PARAMETERS }} # Optional custom build parameters

      # 5. Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build # Adjust this to the actual build output path
